[project]
name = "gnu-mau"
version = "0.1.0"
description = ""
authors = [
    {name = "l337quez",email = "l337quez.dev@gmail.com"}
]
license = {text = "GPL V3"}
requires-python = ">=3.11,<3.15"
dependencies = [
    "pyside6 (>=6.8.0)",
    "markdown2 (>=2.5.4,<3.0.0)",
    "mongita (>=1.2.0,<2.0.0)",
    "numpy (>=2.0.0,<3)",
    "python-dotenv (>=1.0.0)",
    "qtpynodeeditor (>=0.3.3,<0.4.0)",
]


[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyinstaller (>=6.17.0,<7.0.0)"
]
